{% set version = "0.2.1" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-preregr
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/preregr_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/preregr/preregr_{{ version }}.tar.gz
  sha256: 1794290bcf913836f23bf33566c4848efb1e508332bf1bb20c375919ce3d0207

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-cli >=3.0
    - r-jsonlite >=1.7
    - r-rmdpartials >=0.5.8
    - r-yaml >=2.2
  run:
    - r-base
    - r-cli >=3.0
    - r-jsonlite >=1.7
    - r-rmdpartials >=0.5.8
    - r-yaml >=2.2

test:
  commands:
    - $R -e "library('preregr')"           # [not win]
    - "\"%R%\" -e \"library('preregr')\""  # [win]

about:
  home: https://r-packages.gitlab.io/preregr
  license: GPL-3.0-or-later
  summary: Preregistrations, or more generally, registrations, enable explicit timestamped and (often but not necessarily publicly) frozen documentation of plans and expectations as well as decisions and justifications. In research, preregistrations are commonly used to clearly document plans and facilitate justifications
    of deviations from those plans, as well as decreasing the effects of publication bias by enabling identification of research that was conducted but not published. Like reporting guidelines, (pre)registration forms often have specific structures that facilitate systematic reporting of important items. The 'preregr' package
    facilitates specifying (pre)registrations in R and exporting them to a human-readable format (using R Markdown partials or exporting to an 'HTML' file) as well as human-readable embedded data (using 'JSON'), as well as importing such exported (pre)registration specifications from such embedded 'JSON'.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
